spryker-sdk/spryk

README.md
src/SprykerSdk/Spryk/Console/AbstractSprykConsole.php
src/SprykerSdk/Spryk/Console/SprykBuildConsole.php
src/SprykerSdk/Spryk/Console/SprykDumpConsole.php
src/SprykerSdk/Spryk/Console/SprykRunConsole.php
tests/SprykerSdkTest/Spryk/Console/SprykDumpTest.php
tests/_support/SprykConsoleTester.php

https://spryker.atlassian.net/browse/DT-835

DT-835 Simplified help commands

---

src/SprykerSdk/Spryk/Model/Spryk/Definition/Argument/Collection/ArgumentCollection.php
src/SprykerSdk/Spryk/Model/Spryk/Definition/Argument/Collection/ArgumentCollectionInterface.php
src/SprykerSdk/Spryk/Model/Spryk/Definition/SprykDefinition.php
src/SprykerSdk/Spryk/Model/Spryk/Definition/SprykDefinitionInterface.php

Follow https://github.com/spryker-sdk/spryk/pull/13/files

Fix chainable typehinting

---

composer.json
config/spryk/spryks/Spryker/Service/AddService.yml
config/spryk/spryks/Spryker/Service/AddServiceDependencyProvider.yml
config/spryk/spryks/Spryker/Service/AddServiceFactory.yml
config/spryk/spryks/Spryker/Service/AddServiceInterface.yml
config/spryk/templates/Service/Service.php.twig
config/spryk/templates/Service/ServiceDependencyProvider.php.twig
config/spryk/templates/Service/ServiceFactory.php.twig
config/spryk/templates/Service/ServiceInterface.php.twig
tests/SprykerSdkTest/Spryk/Integration/Service/AddServiceDependencyProviderTest.php
tests/SprykerSdkTest/Spryk/Integration/Service/AddServiceFactoryTest.php
tests/SprykerSdkTest/Spryk/Integration/Service/AddServiceInterfaceTest.php
tests/SprykerSdkTest/Spryk/Integration/Service/AddServiceTest.php

- Developer(s): @stereomon
- Ticket: https://spryker.atlassian.net/browse/TE-2031
- Academy PR: ACADEMY_URL_HERE
- Release Group: URL_HERE
Spryk                 | patch (currently 0.x)  |                       |
Added Spryks for easier creating Service related classes.
- Added Service related spryks.

TE-2031 Add Service layer spryks

---

.travis.yml
composer.json
config/spryk/spryks/Spryker/AddModuleEditorconfig.yml
config/spryk/templates/README.md.twig
config/spryk/templates/editorconfig.twig
config/spryk/templates/gitignore.twig
config/spryk/templates/phpstan.json.twig
config/spryk/templates/tooling.yml.twig
config/spryk/templates/travis.yml.twig
src/SprykerSdk/Spryk/Console/SprykBuildConsole.php
src/SprykerSdk/Spryk/Console/SprykDumpConsole.php
src/SprykerSdk/Spryk/Console/SprykRunConsole.php

- Developer(s): @dereuromark
- Ticket: https://spryker.atlassian.net/browse/TE-4572
- Release: https://release.spryker.com/release/pull-request-sdk/Spryk/35
Spryk                 | patch (currently 0.x)  |                       |
{skip}
Bugfixes
Fixed signatures of Commands.

TE-4572 Add PHP74 and new split checks

---

.gitattributes
.gitignore

meta files

---

composer.json
config/spryk/templates/Glue/GlueFactoryMethod.php.twig
config/spryk/templates/Zed/Business/MethodBusinessFactory.php.twig

CR https://spryker.atlassian.net/browse/TE-7187
https://github.com/spryker/development-core/pull/26
https://github.com/spryker-sdk/spryk/pull/45
https://github.com/spryker/silexphp/pull/34
https://github.com/spryker/spryker-shop/pull/1727
https://github.com/spryker/spryker/pull/7449
https://github.com/spryker/suite-nonsplit/pull/4462

TE-5394 Twig v3 Update

---

config/spryk/templates/gitattributes.twig

See https://php.watch/articles/composer-gitattributes
```
diff --git a/src/Pyz/Client/AvailabilityStorage/AvailabilityStorageDependencyProvider.php b/src/Pyz/Client/AvailabilityStorage/AvailabilityStorageDependencyProvider.php
index 5789c638b6..f12a3e371b 100644
--- a/src/Pyz/Client/AvailabilityStorage/AvailabilityStorageDependencyProvider.php
+++ b/src/Pyz/Client/AvailabilityStorage/AvailabilityStorageDependencyProvider.php
@@ -20,7 +20,7 @@ class AvailabilityStorageDependencyProvider extends SprykerAvailabilityStorageDe
{
return [
new ProductOfferAvailabilityStorageStrategyPlugin(),
-            new ProductConfigurationAvailabilityStorageStrategyPlugin(),
+            new ProductConfigurationAvailabilityStorageStrategyPlugin()
];
}
```
becomes
```
diff --git …
```

Add gitattributes php diff

---

composer.json
dependency.json
src/SprykerSdk/Spryk/Model/Spryk/Builder/Constant/ConstantSpryk.php
src/SprykerSdk/Spryk/Model/Spryk/Builder/Navigation/NavigationSpryk.php
src/SprykerSdk/Spryk/Model/Spryk/Builder/Transfer/TransferSpryk.php
src/SprykerSdk/Spryk/Model/Spryk/Filter/CamelCaseFilter.php
src/SprykerSdk/Spryk/Model/Spryk/Filter/CamelCaseToWhitespaceFilter.php
src/SprykerSdk/Spryk/Model/Spryk/Filter/DashToCamelCaseFilter.php
src/SprykerSdk/Spryk/Model/Spryk/Filter/DashToUnderscoreFilter.php
src/SprykerSdk/Spryk/Model/Spryk/Filter/DasherizeFilter.php
src/SprykerSdk/Spryk/Model/Spryk/Filter/UnderscoreFilter.php

- Developer(s): @romanhavrylko
- Ticket: https://spryker.atlassian.net/browse/TE-7666
Spryk           | patch                 | Laminas              |

TE-7819 Replaced Zend usage

---

.travis.yml
src/SprykerSdk/Spryk/Model/Spryk/Builder/Template/Renderer/TemplateRenderer.php

- Jira issue: https://spryker.atlassian.net/browse/TE-7723

TE-7723 Fix broken master for spryker-sdk/spryk

---

composer.json
dependency.json

- Developer(s): @AsonUnique
- Ticket: https://spryker.atlassian.net/browse/TE-7664
- Academy PR: ACADEMY_URL_HERE
- Release Group: https://release.spryker.com/release-groups/view/3112
Spryk                 | patch {skip} (currently 0.x)  |                       |

TE-7664 Fix travis issues

---

.editorconfig
composer.json
config/spryk/templates/composer.json.twig

- Developer(s): @stereomon
- Ticket: https://spryker.atlassian.net/browse/TE-9105
- Academy PR: ACADEMY_URL_HERE
- Release Group: URL_HERE
- merge: merge
Spryk                 | patch (currently 0.x)  |                       |
Fixes
- Adjusted composer.json template to use four spaces instead of two.

TE-9126 Updated composer.json template

---

config/spryk/spryk.yml
config/spryk/spryks/Spryker/AddDataImportModule.yml
config/spryk/spryks/Spryker/AddDefaultModule.yml
config/spryk/spryks/Spryker/AddGuiModule.yml
config/spryk/spryks/Spryker/AddModule.yml
config/spryk/spryks/Spryker/AddUtilModule.yml
config/spryk/spryks/Spryker/AddYvesModule.yml
config/spryk/spryks/Spryker/Client/AddClient.yml
config/spryk/spryks/Spryker/CopyModule.yml
config/spryk/spryks/Spryker/Service/AddService.yml
src/SprykerSdk/Spryk/Console/SprykDumpConsole.php
src/SprykerSdk/Spryk/Model/Spryk/Configuration/ConfigurationFactory.php
src/SprykerSdk/Spryk/Model/Spryk/Configuration/Loader/SprykConfigurationLoader.php
src/SprykerSdk/Spryk/Model/Spryk/Configuration/Validator/Rules/LevelRule.php
src/SprykerSdk/Spryk/Model/Spryk/Dumper/SprykDefinitionDumper.php
src/SprykerSdk/Spryk/Model/Spryk/Dumper/SprykDefinitionDumperInterface.php
src/SprykerSdk/Spryk/SprykConfig.php
src/SprykerSdk/Spryk/SprykFacade.php
src/SprykerSdk/Spryk/SprykFacadeInterface.php
tests/SprykerSdkTest/Spryk/Console/SprykDumpTest.php
tests/_support/SprykTester.php

- Developer(s): @oleksandr-stoilovskyi
- Ticket: https://spryker.atlassian.net/browse/APPS-8
- Academy PR: -
- Release Group: -
Spryk               | minor                 |            |
Improvements
- Adjusted `SprykFacadeInterface::getSprykDefinitions()` so now it accepts optional parameter level which filters the result instead of no optional parameters and no filtering by level.
- Impacted `SprykDumpConsole` with facade changes.

APPS-8 Hide Spryks details

---

config/spryk/spryks/Spryker/Yves/AddYvesPage.yml

- Developer(s): @oleksandr-stoilovskyi
- Ticket: https://spryker.atlassian.net/browse/APPS-9
Spryk               | minor                 |            |
Improvements
- Added new spryk: AddYvesPage

APPS-9 added AddYvesPage spryk

---

config/spryk/templates/gitattributes.twig

- Developer(s): @olhalivitchuk
- Ticket: https://spryker.atlassian.net/browse/TE-8690
- Academy PR: ACADEMY_URL_HERE
- Release Group: https://release.spryker.com/release-groups/view/3526
- PR Overview: https://release.spryker.com/release/pull-request-sdk/Spryk/69
Improvements
- Adjusted `gitattributes.twig` to create template with `architecture-baseline.json export-ignore` string.

TE-8690: Adjusted gitattributes.twig

---

dependency.json

https://spryker.atlassian.net/browse/TE-10787

TE-10787 Dependency checker fails to detect dependencies missing in code (dev:dependency:find)

---

config/spryk/spryks/Spryker/Zed/Business/AddCrudFacade.yml
config/spryk/spryks/Spryker/Zed/Business/DomainEntity/Reader/AddZedDomainEntityReader.yml
config/spryk/templates/Zed/Business/DomainEntity/Reader/DomainEntityReader.php.twig
tests/SprykerSdkTest/Spryk/Integration/Spryker/Zed/Business/AddCrudFacadeTest.php

Ticket: [APPS-3492](https://spryker.atlassian.net/browse/APPS-3492)

APPS-3492: Added Reader model

---

config/spryk/spryks/Spryker/Zed/Business/AddCrudFacade.yml
config/spryk/spryks/Spryker/Zed/DomainEntity/AddZedDomainEntity.yml
config/spryk/spryks/Spryker/Zed/DomainEntity/AddZedDomainEntityInterface.yml
config/spryk/spryks/Spryker/Zed/DomainEntity/AddZedDomainEntityInterfaceMethod.yml
config/spryk/spryks/Spryker/Zed/DomainEntity/AddZedDomainEntityMethod.yml
config/spryk/templates/Common/Model.php.twig
config/spryk/templates/Common/ModelInterface.php.twig
tests/SprykerSdkTest/Spryk/Integration/Spryker/Zed/Business/AddCrudFacadeTest.php
tests/SprykerSdkTest/Spryk/Integration/Zed/DomainEntity/AddZedDomainEntityInterfaceMethodTest.php
tests/SprykerSdkTest/Spryk/Integration/Zed/DomainEntity/AddZedDomainEntityInterfaceTest.php
tests/SprykerSdkTest/Spryk/Integration/Zed/DomainEntity/AddZedDomainEntityMethodTest.php
tests/SprykerSdkTest/Spryk/Integration/Zed/DomainEntity/AddZedDomainEntityTest.php

https://spryker.atlassian.net/browse/APPS-3556
https://spryker.atlassian.net/browse/APPS-3580

APPS-3483:  APPS-3580: APPS-3556: domain entity and identifier builder

---

config/spryk/spryks/Spryker/Zed/Business/AddCrudFacade.yml
config/spryk/spryks/Spryker/Zed/Persistence/DomainEntity/AddZedDomainEntityPersistenceFactoryMethod.yml
config/spryk/templates/Zed/Persistence/PersistenceFactoryMethod.php.twig
tests/SprykerSdkTest/Spryk/Integration/Spryker/Zed/Business/AddCrudFacadeTest.php
tests/_support/Module/ClassName.php

https://spryker.atlassian.net/browse/APPS-3518

Feature/apps 3483/apps 3518 add persistence factory methods

---

tests/SprykerSdkTest/Spryk/Integration/Spryker/Zed/Business/AddCrudFacadeTest.php

PR for Ticket #APPS-3695
https://spryker.atlassian.net/browse/APPS-3695

improve performance of test

---

.github/workflows/ci.yml

https://spryker.atlassian.net/browse/APPS-4649

APPS-4649 Add strictly run

---

bootstrap.php

Need to have possibility autoload classes from phar

PPLUS-1478: Changed PHPStan namespace to Spryk

---

.github/workflows/ci.yml
README.md
composer.json

- Developer(s): @olhalivitchuk   
- Ticket: https://spryker.atlassian.net/browse/FRW-8801
- Release Group: 
- merge: squash
Spryk             | patch (currently 0.x)          |                       |
Improvements 
- Added `PHP 8.3` support.

FRW-8801 Dropped PHP 8.1 support.
